/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OgPreviewRouteImport } from './routes/og-preview'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as ApiPageMdPageRouteImport } from './routes/api/page-md/$page'
import { Route as ApiLlmsTxtRouteImport } from './routes/api/llms.txt'
import { Route as ApiLlmsFullTxtRouteImport } from './routes/api/llms-full.txt'
import { Route as ApiBlogMdSlugRouteImport } from './routes/api/blog-md/$slug'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OgPreviewRoute = OgPreviewRouteImport.update({
  id: '/og-preview',
  path: '/og-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPageMdPageRoute = ApiPageMdPageRouteImport.update({
  id: '/api/page-md/$page',
  path: '/api/page-md/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmsTxtRoute = ApiLlmsTxtRouteImport.update({
  id: '/api/llms/txt',
  path: '/api/llms/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmsFullTxtRoute = ApiLlmsFullTxtRouteImport.update({
  id: '/api/llms-full/txt',
  path: '/api/llms-full/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogMdSlugRoute = ApiBlogMdSlugRouteImport.update({
  id: '/api/blog-md/$slug',
  path: '/api/blog-md/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/og-preview': typeof OgPreviewRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/api/og': typeof ApiOgRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/api/blog-md/$slug': typeof ApiBlogMdSlugRoute
  '/api/llms-full/txt': typeof ApiLlmsFullTxtRoute
  '/api/llms/txt': typeof ApiLlmsTxtRoute
  '/api/page-md/$page': typeof ApiPageMdPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/og-preview': typeof OgPreviewRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/api/og': typeof ApiOgRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/api/blog-md/$slug': typeof ApiBlogMdSlugRoute
  '/api/llms-full/txt': typeof ApiLlmsFullTxtRoute
  '/api/llms/txt': typeof ApiLlmsTxtRoute
  '/api/page-md/$page': typeof ApiPageMdPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/og-preview': typeof OgPreviewRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/api/og': typeof ApiOgRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/api/blog-md/$slug': typeof ApiBlogMdSlugRoute
  '/api/llms-full/txt': typeof ApiLlmsFullTxtRoute
  '/api/llms/txt': typeof ApiLlmsTxtRoute
  '/api/page-md/$page': typeof ApiPageMdPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/og-preview'
    | '/sitemap.xml'
    | '/work'
    | '/api/og'
    | '/blog/$slug'
    | '/blog/'
    | '/api/blog-md/$slug'
    | '/api/llms-full/txt'
    | '/api/llms/txt'
    | '/api/page-md/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/og-preview'
    | '/sitemap.xml'
    | '/work'
    | '/api/og'
    | '/blog/$slug'
    | '/blog'
    | '/api/blog-md/$slug'
    | '/api/llms-full/txt'
    | '/api/llms/txt'
    | '/api/page-md/$page'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/og-preview'
    | '/sitemap.xml'
    | '/work'
    | '/api/og'
    | '/blog/$slug'
    | '/blog/'
    | '/api/blog-md/$slug'
    | '/api/llms-full/txt'
    | '/api/llms/txt'
    | '/api/page-md/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  OgPreviewRoute: typeof OgPreviewRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkRoute: typeof WorkRoute
  ApiOgRoute: typeof ApiOgRoute
  ApiBlogMdSlugRoute: typeof ApiBlogMdSlugRoute
  ApiLlmsFullTxtRoute: typeof ApiLlmsFullTxtRoute
  ApiLlmsTxtRoute: typeof ApiLlmsTxtRoute
  ApiPageMdPageRoute: typeof ApiPageMdPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og-preview': {
      id: '/og-preview'
      path: '/og-preview'
      fullPath: '/og-preview'
      preLoaderRoute: typeof OgPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/page-md/$page': {
      id: '/api/page-md/$page'
      path: '/api/page-md/$page'
      fullPath: '/api/page-md/$page'
      preLoaderRoute: typeof ApiPageMdPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llms/txt': {
      id: '/api/llms/txt'
      path: '/api/llms/txt'
      fullPath: '/api/llms/txt'
      preLoaderRoute: typeof ApiLlmsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llms-full/txt': {
      id: '/api/llms-full/txt'
      path: '/api/llms-full/txt'
      fullPath: '/api/llms-full/txt'
      preLoaderRoute: typeof ApiLlmsFullTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog-md/$slug': {
      id: '/api/blog-md/$slug'
      path: '/api/blog-md/$slug'
      fullPath: '/api/blog-md/$slug'
      preLoaderRoute: typeof ApiBlogMdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  OgPreviewRoute: OgPreviewRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkRoute: WorkRoute,
  ApiOgRoute: ApiOgRoute,
  ApiBlogMdSlugRoute: ApiBlogMdSlugRoute,
  ApiLlmsFullTxtRoute: ApiLlmsFullTxtRoute,
  ApiLlmsTxtRoute: ApiLlmsTxtRoute,
  ApiPageMdPageRoute: ApiPageMdPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
